openapi: 3.0.3
info:
  title: Retrieve bank account insights for IPP.
  version: 1.0.3.3
  description: This API provides the ability for IPP to retrieve insights from the HMRC Customer Insights Platform for a given bank account and sort code.
paths:
  /bank-account-insights/ipp:
    post:
      summary: Bank Account insights
      description: |
        Retrieve insights for the given Bank Account
      parameters:
        - in: header
          required: true
          name: User-Agent
          description: Any string id
          schema:
            type: string
            pattern: '.+'
            example: ipp
        - in: header
          required: false
          name: X-Tracking-Id
          description: Any string identifying the current session that will be inserted into audit trails.
          schema:
            type: string
            pattern: '.+'
            example: 6d5731a4-c927-4107-b81f-eb88288bf5c9
      requestBody:
        description: Account Details
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - sortCode
                - accountNumber
              properties:
                sortCode:
                  type: string
                  minLength: 6
                  maxLength: 6
                  pattern: '([0-9]+){6}'
                accountNumber:
                  type: string
                  minLength: 8
                  maxLength: 8
                  pattern: '([0-9]+){8}'
                  description: "Account numbers less than 8 digits should be pre-padded with zeros"
              example:
                {
                  "sortCode": "991122",
                  "accountNumber": "12345678"
                }
      responses:
        200:
          description: IPP. The response could be an empty document ('{}') if CIP have not seen the bank account details before.
          headers: { }
          content:
            application/json:
              schema:
                type: object
                required:
                  - sortCode
                  - accountNumber
                  - correlationId
                properties:
                  sortCode:
                    type: string
                    minLength: 6
                    maxLength: 6
                    pattern: '([0-9]+){6}'
                  accountNumber:
                    type: string
                    minLength: 8
                    maxLength: 8
                    pattern: '([0-9]+){8}'
                  correlationId:
                    type: string
                  insights:
                    type: object
                    properties:
                      risk:
                        type: object
                        properties:
                          riskScore:
                            maximum: 100
                            minimum: 0
                            type: number
                            description: Risk score
                          reason:
                            type: string
                            description: Reason for risk score
                      relationships:
                        type: array
                        items:
                          type: object
                          required:
                            - attribute
                            - count
                          properties:
                            attribute:
                              type: string
                              pattern: '.+'
                            count:
                              type: number
                            attributeValues:
                              type: array
                              items:
                                type: object
                                required:
                                  - value
                                  - numOfOccurrences
                                  - lastSeen
                                properties:
                                  value:
                                    type: string
                                    pattern: '.+'
                                  numOfOccurrences:
                                    type: number
                                  lastSeen:
                                    type: string
                                    format: date-time
              examples:
                business_with_person_fullname:
                    value:
                      sortCode: "123456"
                      accountNumber: "12345678"
                      correlationId: 1234567-123456-1234567
                      insights:
                        risk:
                          riskScore: 0
                          reason: ACCOUNT_NOT_ON_WATCH_LIST
                        relationships:
                          - attribute: vrn
                            count: 2
                            attributeValues:
                              - value: AB153474/ASD
                                numOfOccurrences: 4
                                lastSeen: "2023-01-05T13:01:59.123Z"
                              - value: AB978474/ASC
                                numOfOccurrences: 2
                                lastSeen: "2023-01-13T17:01:31.111Z"
                          - attribute: ct_utr
                            count: 1
                            attributeValues:
                              - value: "1341325909"
                                numOfOccurrences: 5
                                lastSeen: "2023-01-05T13:01:59.123Z"
                          - attribute: person_full_name
                            count: 1
                            attributeValues:
                              - value: John Smith
                                numOfOccurrences: 5
                                lastSeen: "2023-02-05T13:01:59.123Z"
                          - attribute: agent_code
                            count: 1
                            attributeValues:
                              - value: FH73K1JE83HFW
                                numOfOccurrences: 2
                                lastSeen: "2023-03-05T13:01:59.123Z"
                business:
                  value:
                    sortCode: "123456"
                    accountNumber: "12345678"
                    correlationId: 1234567-123456-1234567
                    insights:
                      risk:
                        riskScore: 0
                        reason: ACCOUNT_NOT_ON_WATCH_LIST
                      relationships:
                        - attribute: vrn
                          count: 2
                          attributeValues:
                            - value: AB153474/ASD
                              numOfOccurrences: 4
                              lastSeen: "2023-01-05T13:01:59.123Z"
                            - value: AB978474/ASC
                              numOfOccurrences: 2
                              lastSeen: "2023-01-13T17:01:31.111Z"
                        - attribute: ct_utr
                          count: 2
                          attributeValues:
                            - value: "1341325909"
                              numOfOccurrences: 5
                              lastSeen: "2023-01-05T13:01:59.123Z"
                            - value: "1341325910"
                              numOfOccurrences: 2
                              lastSeen: "2023-02-05T13:01:59.123Z"
                        - attribute: agent_code
                          count: 1
                          attributeValues:
                            - value: AB129B564
                              numOfOccurrences: 5
                              lastSeen: "2023-01-05T13:01:59.123Z"
                single_relationship:
                  value:
                    sortCode: "123456"
                    accountNumber: "12345678"
                    correlationId: 1234567-123456-1234567
                    insights:
                      risk:
                        riskScore: 0
                        reason: ACCOUNT_NOT_ON_WATCH_LIST
                      relationships:
                        - attribute: sa_utr
                          count: 1
                          attributeValues:
                            - value: "1341325909"
                              numOfOccurrences: 5
                              lastSeen: "2023-01-05T13:01:59.123Z"
                vrn_with_paye_ref:
                  value:
                    sortCode: "123456"
                    accountNumber: "12345678"
                    correlationId: 1234567-123456-1234567
                    insights:
                      risk:
                        riskScore: 0
                        reason: ACCOUNT_NOT_ON_WATCH_LIST
                      relationships:
                        - attribute: ct_utr
                          count: 1
                          attributeValues:
                            - value: "1341325909"
                              numOfOccurrences: 4
                              lastSeen: "2023-01-05T13:01:59.123Z"
                        - attribute: vrn
                          count: 1
                          attributeValues:
                            - value: AB153474/ASD
                              numOfOccurrences: 4
                              lastSeen: "2023-01-05T13:01:59.123Z"
                        - attribute: paye_ref
                          count: 1
                          attributeValues:
                            - value: "1341325909"
                              numOfOccurrences: 5
                              lastSeen: "2023-01-05T13:01:59.123Z"
        3XX:
          description: |
            The request has been redirected. Clients should follow the redirect using the location header as per the HTTP specification.
        400:
          description: |
            The request was invalid, e.g the account number or sort code was not well formed.
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                    pattern: '.+'
                  desc:
                    type: string
                    pattern: '.+'
                    example: "123456: invalid sortcode."
                    description: Full description of the error, designed to be human readable.
              examples:
                INVALID_SORT_CODE:
                  value: {
                    "code": "INVALID_SORT_CODE",
                    "desc": "A badly formatted, or missing sort code."
                  }
                INVALID_ACCOUNT_NUMBER:
                  value: {
                    "code": "INVALID_ACCOUNT_NUMBER",
                    "desc": "A badly formatted, or missing account number."
                  }
        5XX:
          description: |
            An unexpected server error occurred when processing the request. These are usually temporary and consumers should try again.
